import { RecipeFilters } from 'chaud-devant'

/* Données de démonstration : le hub filtre côté client, il lui faut un
   éventail réaliste — catégories, saisons, temps courts et longs. */
const RECETTES = [
  {
    id: '1',
    slug: 'boeuf-carottes-du-dimanche',
    title: 'Bœuf-carottes du dimanche',
    category: 'Plat',
    seasons: ['automne', 'hiver'],
    minutes: 180,
    prepMinutes: 25,
    difficulty: 'facile',
    angle: null,
    cover: null,
    postUrl: null,
    intro: [],
    ingredients: ['paleron', 'carottes', 'oignons', 'bouquet garni'],
    steps: [],
    publishedAt: null,
  },
  {
    id: '2',
    slug: 'poulet-du-dimanche-pommes-fondantes',
    title: 'Poulet rôti, pommes de terre fondantes',
    category: 'Plat',
    seasons: ['automne'],
    minutes: 90,
    prepMinutes: 15,
    difficulty: 'facile',
    angle: null,
    cover: null,
    postUrl: null,
    intro: [],
    ingredients: ['poulet fermier', 'pommes de terre', 'thym', 'beurre'],
    steps: [],
    publishedAt: null,
  },
  {
    id: '3',
    slug: 'gratin-dauphinois-de-grand-mere',
    title: 'Gratin dauphinois comme chez ma grand-mère',
    category: 'Accompagnement',
    seasons: ['hiver'],
    minutes: 75,
    prepMinutes: 20,
    difficulty: 'facile',
    angle: null,
    cover: null,
    postUrl: null,
    intro: [],
    ingredients: ['pommes de terre', 'crème', 'lait', 'ail', 'muscade'],
    steps: [],
    publishedAt: null,
  },
  {
    id: '4',
    slug: 'oeufs-cocotte-aux-champignons',
    title: 'Œufs cocotte aux champignons',
    category: 'Entrée',
    seasons: ['automne', 'hiver'],
    minutes: 15,
    prepMinutes: 10,
    difficulty: 'facile',
    angle: null,
    cover: null,
    postUrl: null,
    intro: [],
    ingredients: ['œufs', 'champignons de Paris', 'crème', 'ciboulette'],
    steps: [],
    publishedAt: null,
  },
  {
    id: '5',
    slug: 'riz-au-lait-a-la-vanille',
    title: 'Riz au lait à la vanille, comme à la cantine en mieux',
    category: 'Dessert',
    seasons: ['hiver', 'printemps'],
    minutes: 45,
    prepMinutes: 5,
    difficulty: 'facile',
    angle: null,
    cover: null,
    postUrl: null,
    intro: [],
    ingredients: ['riz rond', 'lait entier', 'vanille', 'sucre'],
    steps: [],
    publishedAt: null,
  },
  {
    id: '6',
    slug: 'tomates-farcies-a-partager',
    title: 'Tomates farcies à partager',
    category: 'Plat',
    seasons: ['été'],
    minutes: 60,
    prepMinutes: 30,
    difficulty: 'facile',
    angle: null,
    cover: null,
    postUrl: null,
    intro: [],
    ingredients: ['tomates', 'chair à saucisse', 'riz', 'persil'],
    steps: [],
    publishedAt: null,
  },
]

/** Le hub complet : recherche, puces de filtre, compteur et grille de cartes. */
export const Hub = () => (
  <div className="papier p-8">
    <RecipeFilters recipes={RECETTES} />
  </div>
)
